#!/usr/bin/env python3
"""Collect metadata from the JavaScript-rendered, public FCS publication page.

The script intentionally stays in the public portal. It captures public GetTables
responses generated by the page and never visits the authenticated portal.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse, urlunparse


PUBLIC_URL = "https://fcs.health.gov.il/publicationsCategories/0"
DOCUMENT_URL = "https://fcs.health.gov.il/FCS/GetSpecificDocument"
EXPECTED_HOST = "fcs.health.gov.il"
DOCUMENT_DOWNLOAD_ATTEMPTS = 5
RETRYABLE_DOCUMENT_STATUSES = {403, 408, 425, 429, 500, 502, 503, 504}


def now() -> str:
    return datetime.now(timezone.utc).isoformat()


def parse_post_data(entry: dict) -> dict:
    try:
        return json.loads(entry.get("post_data") or "{}")
    except json.JSONDecodeError:
        return {}


def response_rows(entry: dict) -> list[dict]:
    data = entry.get("json", {}).get("data", [])
    if not data or not isinstance(data[0], list):
        return []
    return [row for row in data[0] if isinstance(row, dict)]


def normalized_items(rows: list[dict]) -> list[dict]:
    items = []
    for row in rows:
        documents = []
        for document in row.get("docs") or []:
            documents.append(
                {
                    "document_name": document.get("documentName", ""),
                    "file_name": document.get("fileName", ""),
                    "file_extension": document.get("fileExt", ""),
                    "issue_date": document.get("issueDate", ""),
                    "guid": document.get("guid", ""),
                    "document_type_code": document.get("documentTypeCode"),
                    "remarks": document.get("remarks", ""),
                    "linked_url": document.get("linkToDocument", ""),
                }
            )
        items.append(
            {
                "info_id": row.get("infoId"),
                "title": row.get("infoTiltle", ""),
                "description": row.get("infoDescription", ""),
                "tags": row.get("infoTags", ""),
                "linked_url": row.get("infoLinkUrl", ""),
                "link_text": row.get("infoLinkAnchorText", ""),
                "created_at": row.get("infoCreateDate", ""),
                "documents": documents,
            }
        )
    return items


def normalized_https_url(value: str) -> str | None:
    value = (value or "").strip()
    if not value:
        return None
    parsed = urlparse(value)
    if parsed.scheme.lower() != "https" or not parsed.hostname:
        return None
    return urlunparse(parsed._replace(scheme="https", fragment=""))


def build_direct_references(
    catalogue: list[dict], source_url: str, denied_hosts: set[str]
) -> list[dict]:
    by_url: dict[str, dict] = {}
    for category in catalogue:
        for item in category.get("items", []):
            candidates = []
            if item.get("linked_url"):
                candidates.append(("infoLinkUrl", item["linked_url"], None))
            for document in item.get("documents", []):
                if document.get("linked_url"):
                    candidates.append(("docs[].linkToDocument", document["linked_url"], document))

            for field, raw_url, document in candidates:
                url = normalized_https_url(raw_url)
                host = (urlparse(url).hostname or "").lower() if url else ""
                eligible = bool(url) and host not in denied_hosts
                record_url = url or raw_url.strip()
                reference = by_url.setdefault(
                    record_url,
                    {
                        "reference_id": hashlib.sha256(record_url.encode("utf-8")).hexdigest()[:20],
                        "url": record_url,
                        "relationship": "direct_fcs_publication_reference",
                        "eligible_for_collection": eligible,
                        "exclusion_reason": (
                            None
                            if eligible
                            else "URL is not public HTTPS or points to a denied host"
                        ),
                        "discovered_from": [],
                    },
                )
                reference["discovered_from"].append(
                    {
                        "source_catalogue_url": source_url,
                        "category_code": category.get("subject_code"),
                        "category": category.get("subject_name"),
                        "item_id": item.get("info_id"),
                        "item_title": item.get("title"),
                        "field": field,
                        "document_guid": document.get("guid") if document else None,
                        "document_name": document.get("document_name") if document else None,
                    }
                )
    return sorted(by_url.values(), key=lambda row: row["url"])


def document_candidates(catalogue: list[dict]) -> list[tuple[dict, dict, dict]]:
    """Return unique FCS-hosted documents while preserving catalogue order."""
    candidates = []
    seen_guids: set[str] = set()
    for category in catalogue:
        for item in category.get("items", []):
            for document in item.get("documents", []):
                guid = (document.get("guid") or "").strip()
                if not guid or guid in seen_guids:
                    continue
                seen_guids.add(guid)
                candidates.append((category, item, document))
    return candidates


def download_fcs_document(
    request_context,
    category: dict,
    item: dict,
    document: dict,
    documents_dir: Path,
    root: Path,
    maximum_bytes: int,
) -> dict:
    guid = (document.get("guid") or "").strip()
    if not guid:
        raise RuntimeError("Document has no GUID")
    response = None
    for attempt in range(1, DOCUMENT_DOWNLOAD_ATTEMPTS + 1):
        response = request_context.post(
            DOCUMENT_URL,
            data={"docType": 26, "docId": guid},
            headers={"Referer": PUBLIC_URL, "Accept": "application/json, text/plain, */*"},
            timeout=120_000,
        )
        if response.status == 200:
            break
        if (
            response.status not in RETRYABLE_DOCUMENT_STATUSES
            or attempt == DOCUMENT_DOWNLOAD_ATTEMPTS
        ):
            raise RuntimeError(
                f"Document request failed with HTTP {response.status} after {attempt} attempt(s)"
            )
        time.sleep(2 ** (attempt - 1))
    if response is None:
        raise RuntimeError("Document request did not return a response")
    payload = response.json()
    encoded = payload.get("data")
    if not isinstance(encoded, str):
        raise RuntimeError("Document response did not contain a base64 data field")
    content = base64.b64decode(encoded, validate=True)
    if len(content) > maximum_bytes:
        raise RuntimeError(f"Document exceeds the {maximum_bytes}-byte policy limit")
    extension = (document.get("file_extension") or ".pdf").strip().lower()
    if not extension.startswith("."):
        extension = f".{extension}"
    if extension == ".pdf" and not content.startswith(b"%PDF-"):
        raise RuntimeError("Downloaded content is not a PDF")
    destination = documents_dir / f"{guid}{extension}"
    destination.write_bytes(content)
    return {
        "collected_at": now(),
        "source_catalogue_url": PUBLIC_URL,
        "request_url": DOCUMENT_URL,
        "category": category.get("subject_name"),
        "item_title": item.get("title"),
        **document,
        "saved_path": destination.relative_to(root).as_posix(),
        "bytes": len(content),
        "sha256": hashlib.sha256(content).hexdigest(),
        "http_status": response.status,
        "status": "downloaded",
    }


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")

    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--show-browser", action="store_true")
    parser.add_argument("--limit-categories", type=int)
    parser.add_argument(
        "--download-match",
        help="Download the first public document whose title or filename contains this text",
    )
    parser.add_argument(
        "--download-all-documents",
        action="store_true",
        help="Download every unique FCS-hosted document discovered in the crawled categories",
    )
    parser.add_argument(
        "--browser-channel",
        default="chrome",
        help="Installed browser channel (default: chrome); use 'bundled' for Playwright Chromium",
    )
    args = parser.parse_args()
    if args.download_match and args.download_all_documents:
        parser.error("--download-match and --download-all-documents are mutually exclusive")

    root = args.project_root.resolve()
    policy_path = root / "config" / "crawl_policy.json"
    policy = json.loads(policy_path.read_text(encoding="utf-8"))
    entrypoints = policy.get("entrypoints", [])
    if entrypoints != [PUBLIC_URL]:
        raise ValueError("Crawler entry point does not match config/crawl_policy.json")
    service_hosts = {host.lower() for host in policy.get("fcs_service_hosts", [])}
    denied_hosts = {host.lower() for host in policy.get("denied_hosts", [])}
    if EXPECTED_HOST not in service_hosts or EXPECTED_HOST in denied_hosts:
        raise ValueError("FCS public host is not permitted by crawl policy")
    if "fcsportal.health.gov.il" not in denied_hosts:
        raise ValueError("Authenticated FCS portal must remain denied")
    os.environ.setdefault("PLAYWRIGHT_BROWSERS_PATH", str(root / ".playwright-browsers"))

    try:
        from playwright.sync_api import TimeoutError as PlaywrightTimeoutError
        from playwright.sync_api import sync_playwright
    except ImportError:
        print(
            "Playwright is not installed. Run: python -m pip install -r "
            "requirements-phase1.txt; python -m playwright install chromium",
            file=sys.stderr,
        )
        return 2

    metadata_dir = root / "data" / "metadata"
    raw_dir = root / "data" / "raw" / "fcs_publications"
    documents_dir = root / "data" / "raw" / "fcs_documents"
    report_dir = root / "reports"
    metadata_dir.mkdir(parents=True, exist_ok=True)
    raw_dir.mkdir(parents=True, exist_ok=True)
    documents_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)

    captured: list[dict] = []
    catalogue: list[dict] = []
    downloads: list[dict] = []
    download_errors: list[dict] = []
    selected_candidates: list[tuple[dict, dict, dict]] = []

    with sync_playwright() as pw:
        launch_options = {"headless": not args.show_browser}
        if args.browser_channel != "bundled":
            launch_options["channel"] = args.browser_channel
        browser = pw.chromium.launch(**launch_options)
        context = browser.new_context(locale="he-IL", ignore_https_errors=True)
        page = context.new_page()
        print(f"Opening {PUBLIC_URL}", flush=True)

        def capture_response(response) -> None:
            request = response.request
            parsed = urlparse(response.url)
            if (parsed.hostname or "").lower() not in service_hosts:
                return
            if not any(term in response.url for term in ("GetTables", "GetSpecificDocument")):
                return
            entry = {
                "captured_at": now(),
                "url": response.url,
                "method": request.method,
                "status": response.status,
                "post_data": request.post_data,
            }
            # Keep catalogue evidence, but never duplicate large base64 document
            # bodies in the raw response capture.
            if "GetTables" in response.url:
                try:
                    entry["json"] = response.json()
                except Exception:
                    entry["body_not_json"] = True
            else:
                entry["body_omitted"] = True
            captured.append(entry)

        page.on("response", capture_response)
        page.goto(PUBLIC_URL, wait_until="domcontentloaded", timeout=60_000)
        page.locator("mat-row.clickable-row").first.wait_for(state="visible", timeout=45_000)
        categories = page.locator("mat-row.clickable-row").evaluate_all(
            """rows => rows.map(row => {
                const cells = Array.from(row.querySelectorAll('[role=cell]'));
                return {
                    subject_name: (cells[0]?.textContent || '').trim(),
                    description: (cells[1]?.textContent || '').trim()
                };
            })"""
        )
        category_response = next(
            (
                entry
                for entry in reversed(captured)
                if parse_post_data(entry).get("functionCode") == 94
            ),
            {},
        )
        category_codes = {
            row.get("subjectName"): row.get("subjectCode")
            for row in response_rows(category_response)
        }
        for category in categories:
            category["subject_code"] = category_codes.get(category["subject_name"])
        if args.limit_categories:
            categories = categories[: args.limit_categories]
        print(f"Found {len(categories)} categories", flush=True)

        for category in categories:
            print(f"Collecting {category['subject_name']}", flush=True)
            for attempt in range(3):
                try:
                    page.goto(PUBLIC_URL, wait_until="domcontentloaded", timeout=60_000)
                    rows = page.locator("mat-row.clickable-row")
                    rows.first.wait_for(state="visible", timeout=45_000)
                    target = rows.filter(has_text=category["subject_name"]).first
                    target.click(timeout=15_000)
                    page.locator("h1").wait_for(state="visible", timeout=30_000)
                    break
                except PlaywrightTimeoutError:
                    if attempt == 2:
                        catalogue.append({**category, "status": "timeout", "items": []})
                    page.reload(wait_until="domcontentloaded", timeout=60_000)
            else:
                continue

            expanders = page.locator("button:has(img[src*='add'])")
            for index in range(expanders.count()):
                try:
                    expanders.nth(index).click(timeout=5_000)
                except PlaywrightTimeoutError:
                    pass

            item_response = next(
                (
                    entry
                    for entry in reversed(captured)
                    if parse_post_data(entry).get("functionCode") == 95
                    and parse_post_data(entry).get("certificateNum")
                    == category.get("subject_code")
                ),
                {},
            )
            items = normalized_items(response_rows(item_response))
            catalogue.append(
                {
                    **category,
                    "status": "collected",
                    "items": items,
                }
            )

        candidates = document_candidates(catalogue)
        if args.download_all_documents:
            selected_candidates = candidates
        elif args.download_match:
            needle = args.download_match.casefold()
            matches = [
                (category, item, document)
                for category, item, document in candidates
                if needle
                in " ".join(
                    [
                        item.get("title", ""),
                        document.get("document_name", ""),
                        document.get("file_name", ""),
                    ]
                ).casefold()
            ]
            if not matches:
                raise RuntimeError(f"No public FCS document matched: {args.download_match}")
            selected_candidates = matches[:1]

        maximum_bytes = int(policy["rules"]["maximum_download_bytes"])
        for index, (category, item, document) in enumerate(selected_candidates, start=1):
            name = document.get("document_name") or document.get("file_name") or document.get("guid")
            print(f"Downloading document {index}/{len(selected_candidates)}: {name}", flush=True)
            try:
                downloads.append(
                    download_fcs_document(
                        page.request,
                        category,
                        item,
                        document,
                        documents_dir,
                        root,
                        maximum_bytes,
                    )
                )
            except Exception as exc:
                error = {
                    "collected_at": now(),
                    "source_catalogue_url": PUBLIC_URL,
                    "request_url": DOCUMENT_URL,
                    "category": category.get("subject_name"),
                    "item_title": item.get("title"),
                    **document,
                    "status": "error",
                    "error": f"{type(exc).__name__}: {exc}",
                }
                download_errors.append(error)
                print(f"ERROR downloading {name}: {error['error']}", file=sys.stderr, flush=True)
            time.sleep(0.5)

        (raw_dir / "captured_public_responses.json").write_text(
            json.dumps(captured, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        browser.close()

    inventory = {
        "collected_at": now(),
        "scope_id": policy["scope_id"],
        "source_url": PUBLIC_URL,
        "scope": "Public FCS portal and exact sources directly referenced by its publications",
        "categories": catalogue,
        "downloads": downloads,
        "download_errors": download_errors,
    }
    output = metadata_dir / "fcs_publication_inventory.json"
    output.write_text(json.dumps(inventory, ensure_ascii=False, indent=2), encoding="utf-8")
    references = build_direct_references(catalogue, PUBLIC_URL, denied_hosts)
    references_path = metadata_dir / "fcs_direct_references.json"
    references_path.write_text(
        json.dumps(
            {
                "collected_at": now(),
                "scope_id": policy["scope_id"],
                "source_catalogue_url": PUBLIC_URL,
                "references": references,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    print(f"Wrote {output} with {len(catalogue)} categories", flush=True)
    print(f"Wrote {references_path} with {len(references)} direct external references", flush=True)
    if selected_candidates:
        manifest_path = metadata_dir / "fcs_document_downloads.json"
        manifest_path.write_text(
            json.dumps(
                {
                    "collected_at": now(),
                    "scope_id": policy["scope_id"],
                    "documents": downloads,
                    "errors": download_errors,
                },
                ensure_ascii=False,
                indent=2,
            ),
            encoding="utf-8",
        )
        report_path = report_dir / "fcs_crawl_run.md"
        report_path.write_text(
            "\n".join(
                [
                    "# FCS browser crawl",
                    "",
                    f"Run at: {now()}",
                    "",
                    "## Result",
                    "",
                    f"- Browser mode: {'visible Chrome' if args.show_browser else 'headless Chrome'}.",
                    f"- Public categories rendered: {len(category_codes)}.",
                    f"- Categories crawled in this run: {len(catalogue)}.",
                    f"- Publication items captured: {sum(len(c.get('items', [])) for c in catalogue)}.",
                    f"- Exact external references discovered from FCS records: {len(references)}.",
                    f"- FCS-hosted documents selected: {len(selected_candidates)}.",
                    f"- FCS-hosted documents downloaded: {len(downloads)}.",
                    f"- Document download errors: {len(download_errors)}.",
                    f"- Downloaded bytes: {sum(row['bytes'] for row in downloads):,}.",
                    "",
                    "The catalogue was rendered in Chrome, its public GetTables responses were captured, and selected public documents were retrieved through the same FCS document action used by the page.",
                    "",
                    "This proves technical feasibility for browser-assisted collection of the public portal. The endpoint remains undocumented, so the collector preserves raw responses and provenance and should be monitored for contract changes.",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        print(f"Wrote {manifest_path}", flush=True)
        print(f"Wrote {report_path}", flush=True)
    return 1 if download_errors else 0


if __name__ == "__main__":
    sys.exit(main())
